#ifndef CONFIGURATION_FILE
#define CONFIGURATION_FILE

// settings
#define TRAIN_CICLES 10000
#define PARAM_INTENSITY_CORRECT 0.02
#define PARAM_INTENSITY_ERROR 0.01
#define PARAM_BACK_PROPAGATION 0.001
#define VERBOSE_TRAIN false

#endif  // CONFIGURATION_FILE